# Generated by Django 5.2.4 on 2025-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authentication_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="tournaments_played",
            field=models.IntegerField(default=0),
        ),
    ]
