# Generated by Django 5.2.4 on 2025-07-19 17:43

import users.authentication_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_authentication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="level3authenticationrequest",
            name="text_to_read",
            field=models.CharField(
                default=users.authentication_models.generate_random_text, max_length=10
            ),
        ),
    ]
