# Generated by Django 5.2.4 on 2025-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_tournament_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tier",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("diamond", "Diamond"),
                ],
                default="bronze",
                max_length=10,
            ),
        ),
    ]
