# Generated by Django 5.2.4 on 2025-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_tournament_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournaments_played_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournaments_played_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
